### ISSUE TITLE
New installation results in white-screen

### ISSUE THREAD

**Issue by rparrish** [123andy/redcap-autonotify2#1]
...when accessing `<HOSTNAME/redcap/plugins/autonotify/index.php`

Server details:
 - PHP: 7.1.3
 - IIS: 7.5
 - OS: Window 2008R2

**Comment by 123andy** [comment]
Did you look at the common.php file - I believe there is a logging variable that might not be correct in your new server.  Also, identify your php_error_log file and check it for comments.

**Comment by rparrish** [comment]
Figured it out - I wasn't using the plugin correctly.
